### PR TITLE
[rs256] Add RS256, remove keylen check, update tests

### PR DESCRIPTION
**Pull request by tjamison**
Add support for RS256 alg type
Add tests for signing, verifying RS256 tokens
Remove check on key length, which is not part of the JWT standard
Remove parameters from main() in tests, which failed with -pedantic

Signed-off-by: Tatiana Jamison <tjamison@jaguarlandrover.com>

### CODE REVIEW

**Comment by davidraleigh** [comment]
This seems like it's failing tests even though Travis CI has it as passing.

https://travis-ci.org/benmcollins/libjwt/jobs/163142238#L419

When I run these changes I get a failure at 

https://github.com/tjamison/libjwt/blob/4b840ea73f17334f468760f1f75cd52e035dbf89/tests/jwt_encode.c#L207

```bash
/opt/src/libjwt/bin/jwt_encode
Running suite(s): LibJWT Encode
87%: Checks: 8, Failures: 1, Errors: 0
/opt/src/libjwt/tests/jwt_encode.c:35:P:jwt_encode:test_jwt_encode_fp:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:63:P:jwt_encode:test_jwt_encode_str:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:95:P:jwt_encode:test_jwt_encode_hs256:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:128:P:jwt_encode:test_jwt_encode_hs384:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:161:P:jwt_encode:test_jwt_encode_hs512:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:207:F:jwt_encode:test_jwt_encode_rs256:0: Assertion 'out != ((void *)0)' failed
/opt/src/libjwt/tests/jwt_encode.c:243:P:jwt_encode:test_jwt_encode_change_alg:0: Passed
/opt/src/libjwt/tests/jwt_encode.c:282:P:jwt_encode:test_jwt_encode_invalid:0: Passed
```

**Comment by davidraleigh** [comment]
hey,  @tjamison , I see the progress you're making and it looks great. Until you merge in Ben's changes the Travis CI test run won't be triggered.

**Comment by davidraleigh** [comment]
Even though there is a green check mark for TravisCI, if you look at the log there are still a couple of failures (just search the log for `Segmentation fault`).
https://travis-ci.org/benmcollins/libjwt/builds/151357923#L371

But I think this might be an Ubuntu version problem. I just upgraded my docker image from 15.10 (test failures for RSA) to 16.04 and now all my tests pass. 12.04 is what the TravisCI server is, and maybe that's why it fails?

nice work @tjamison , Thank you!

**Comment by tjamison** [comment]
I've been scratching my head over the failures in travis-ci and codecov. When I run the tests locally from a clean pull, I get 88.7% coverage by line and 100% coverage by function.

**Comment by benmcollins** [comment]
I've been thinking about this in regards to the key length. Personally, I think it's wrong to remove the check. If you are passing in a key that is less than the expected length (e.g. 24 bytes for HS256), then you are effectively reducing the key strength. This isn't a JWT issue to enforce, it is a cryptographic one.

Crypto best practices will tell you not to use a "passphrase" directly for an HMAC key. Instead it should be passed to the proper SHA routine to produce a key of proper length (and more importantly, of proper entropy and dispersion).

E.g. if you want to use `this is my passphrase` as an HS256 key, then perform a SHA256() on that passphrase and use the resulting 256-bit (32-byte) result as the actual key for HS256.

I don't think I want to create a library that condones the use of shorter key lengths. Likewise, if you want to go that route, I want to force the user to create a 32-byte array padded with zeroes at the end to do so, thus making them work for their silliness.

**Comment by benmcollins** [comment]
Apparently, I'm the idiot. HMAC routines use SHA1/2 to generate a proper key already. The passed key material isn't used directly.

I need to rethink that whole thing and rework it over the weekend.

**Comment by benmcollins** [comment]
I've removed the key length restrictions (other than to enforce that it is > 0 if a key is present or the alg is not NONE).

I'm closing out this pull request and invite you to rework the RS routines as a separate pull request against master.

Thanks

**Comment by tjamison** [comment]
Will do -- thanks for the response.

**Pull request closed without merging**
