### PR TITLE
Integration with jansson library

### PR DESCRIPTION
**Pull request by babelouest**
Add jwt_add_grants_json_object and jwt_dump_json functions to manipulate json_t * structures

### CODE REVIEW

**Comment by benmcollins** [comment]
Aside from the conflicts, I'm trying to avoid exposing Jansson through LibJWT. This encounters lots of possible ABI/API issues depending on which Jansson library we may be linked against or may be exposed on the system. I want to avoid having to worry about all of the underlying issues of that.

We have another pull request that requires some work where we can load/dump a JSON string, which I think is more agnostic to the underlying JSON library that LibJWT may be using and doesn't expose any ABI/API issues.

**Comment by babelouest** [comment]
I understand your position but I use jansson in my own projects and it would  be useful to manipulate the `json_t` object directly instead of doing:
`json_t * -> char * -> json_t *`

**Comment by tjamison** [comment]
@babelouest: You might consider adding a helper function to your project, as I've done in mine:

```
json_t *get_json_grant ( jwt_t *jwt, const char *grant )
{
    if( !jwt || !grant || !strlen(grant) ) { return NULL; }

    /* get token in plaintext */
    char *plaintext = jwt_dump_str( jwt, 0 );

    /* store pointer to free memory */
    char *start = plaintext;

    /* advance past header */
    while( *plaintext++ != '.');

    json_t *body = json_loads( plaintext, JSON_REJECT_DUPLICATES, NULL );

    free( start );

    json_t *claim = json_object_get( body, grant );

    json_t *new = json_deep_copy( claim );

    json_decref( body );

    return new;
}
```

**Comment by benmcollins** [comment]
I do as well, and as much as I'd like to do that, the prospect of ABI/API issues is very real and very problematic to over come, even if it provides some convenience. I do appreciate your work on this, but I have to remain firm on not exposing Jansson through LibJWT.

**Pull request closed without merging**
