### PR TITLE
Add clang-format to make it easier for contributors to style their code correctly before submitting PR's

### PR DESCRIPTION
**Pull request by TomzBench**
clang-format is a code style guide enforcement tool. I notice some PR's get slowed down because of style considerations and I think a style management tool like clang-format is useful for any maintainer trying to enforce style rules while managing contributions.

This PR adds .clang-format configuration to configure the style rules. I did my best to match the rules based on the observed formatting.  Potential code changes if you were to run the formatter would look like this:

```
 libjwt/jwt-gnutls.c   |  62 +++---
 libjwt/jwt-openssl.c  |  36 ++--
 libjwt/jwt-private.h  |   6 +-
 libjwt/jwt-wincrypt.c | 529 ++++++++++++++++----------------------------------
 libjwt/jwt.c          |  44 ++---
 5 files changed, 236 insertions(+), 441 deletions(-)
```

Most of these changes are because of inconsistencies in the way the current code base is formatted. For example, currently, some pointers are right justified and some pointers are left justified.  This is expected because it's not possible to manually maintain style guide rules with 100% accuracy with out a program to automate it for you.

(I think the wincrypt code style guide seems different then the rest of the repo. - so that is the reason for the large diff there)

Note if you accept the PR you can run the tool and experiment with the different options. I think that is the maintainers role so I did not make any code edits in the PR.

### CODE REVIEW

**Comment by benmcollins** [comment]
Can I see  the diff from running this on the current code?

**Comment by TomzBench** [comment]
I attached the diff here instead of committing. 

[format-changes.txt](https://github.com/benmcollins/libjwt/files/4159867/format-changes.txt)

**Comment by benmcollins** [comment]
Ones like this:

    -#define APPEND_STR(__buf, __str) do {          \
    -       int ret = __append_str(__buf, __str);   \
    -       if (ret)                                \
    -               return ret;                     \
    -} while(0)
    +#define APPEND_STR(__buf, __str)                                                                   \
    +       do {                                                                                       \
    +               int ret = __append_str(__buf, __str);                                              \
    +               if (ret)                                                                           \
    +                       return ret;                                                                \
    +       } while (0)

I don't like. I would rather it use tabs to offset the trailing backslashes and not spaces and to keep them as close to the code as possible (like what is originally there).

Also, seems the line length is like 100. I like to keep lines no longer than 78 characters.

Everything else looks pretty good. Now if you can point me at an integration on GitHub that will enforce it :)

**Comment by TomzBench** [comment]
[format-diff.txt](https://github.com/benmcollins/libjwt/files/4160227/format-diff.txt)

I changed the settings a bit to max column width at 78. I also turned the formatting off near certain macros. You can selectively disable formatting by surrounding your code with: ```// clang-format off``` and ```// clang-format on```

So your do {} loop macros look the same with selective disabled formatting. Also this diff sample has a lot more diffs then before. Because of the max col violation in the current code base.

As far as integration goes, there is CI integration that will fail code that has diffs after formatting. I never set that up though I just make the contributor do it or I do it manually.

**Comment by TomzBench** [comment]
Also I find this to be risky:

```
+	if (json_object_set_new(
+		jwt_valid->req_grants, grant, json_boolean(val)))
 		return EINVAL;
```
Because of max column shrinkage it now bumped the if statement onto 2 lines. And in cases like these I usually always force { } brackets around one line if's.  The tool will automatically surround all one line if statements with brackets if you want it to. Most editors support clang-format so you can experiment with it and see what's best to your liking.

**Comment by benmcollins** [comment]
Closing because this now has conflicts that need to be resolved.

**Pull request closed without merging**
