### PR TITLE
Fix Conditionals in Automake Build

### PR DESCRIPTION
**Pull request by devopsec**
- make sure default conditionals for `HAVE_GNUTLS` and `HAVE_OPENSSL` are always run

### CODE REVIEW

**Comment by devopsec** [comment]
@benmcollins tested on debian12, this fixes the missing conditional when using `./configure` without explicitly specifying TLS version to use.

**Comment by benmcollins** [comment]
Thanks for the PR. However, I'm unsure why you're seeing this. I test a lot of builds without explicitly setting `--with-openssl` or `--with-gnutls`.

**Comment by devopsec** [comment]
Not sure why those builds were working and mine were not, I was just building from master today on a fresh debian12 install and saw autoreconf failing with:

```
configure: error: conditional "HAVE_GNUTLS" was never defined.
Usually this means the macro was only invoked conditionally.
```

This is actually failing at a different point now after the latest commits.  
ref: https://github.com/benmcollins/libjwt/blob/9aad71b03459b1b9deb4ec00d90ef85eb1986c05/configure.ac#L28  
The default was `with_openssl=check`

In case you wanted to reproduce yourself (fresh debian12 box, digital ocean image in my case):

```
apt install -y build-essential pkg-config dh-autoreconf git libssl-dev libjansson-dev &&
git clone https://github.com/benmcollins/libjwt.git /usr/local/src/libjwt &&
cd /usr/local/src/libjwt &&
git checkout a191ebf &&
autoreconf -i &&
./configure --prefix=/usr &&
make -j $(nproc) &&
make -j $(nproc) install
```

**Comment by benmcollins** [comment]
I ran this on macOS (clang) and Ubuntu 22.04 (x64_64). Both completed without errors (minus the install command).

Your referenced checkout and master both work fine for me. Can you retest on tip?

**Comment by devopsec** [comment]
Had a client email today with the same issue on Debian12.  
Maybe it is a difference in packages already present on the images we are building off?

I am assuming you meant build off master again by tip correct?

Re-tested with new debian12 (x86_64) instance on digital ocean and got the same result.

```
apt install -y build-essential pkg-config dh-autoreconf git libssl-dev libjansson-dev &&
git clone https://github.com/benmcollins/libjwt.git /usr/local/src/libjwt &&
cd /usr/local/src/libjwt &&
autoreconf -i &&
./configure --prefix=/usr &&
make -j $(nproc) &&
make -j $(nproc) install
```

I attached the output from configure.
[build-output.log](https://github.com/user-attachments/files/18186829/build-output.log)

Maybe those builds that passed had gnutls by default instead?

Here's the packages I am seeing related to SSL after the above commands:

```
root@debian12-tmp:/usr/local/src/libjwt# dpkg -l |grep -i ssl
ii  libcurl4:amd64                  7.88.1-10+deb12u7              amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libssl-dev:amd64                3.0.15-1~deb12u1               amd64        Secure Sockets Layer toolkit - development files
ii  libssl3:amd64                   3.0.15-1~deb12u1               amd64        Secure Sockets Layer toolkit - shared libraries
ii  libzstd1:amd64                  1.5.4+dfsg2-5                  amd64        fast lossless compression algorithm
ii  openssl                         3.0.15-1~deb12u1               amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python3-certifi                 2022.9.24-1                    all          root certificates for validating SSL certs and verifying TLS hosts (python3)
ii  zstd                            1.5.4+dfsg2-5                  amd64        fast lossless compression algorithm -- CLI tool
root@debian12-tmp:/usr/local/src/libjwt# openssl version
OpenSSL 3.0.15 3 Sep 2024 (Library: OpenSSL 3.0.15 3 Sep 2024)
```

**Comment by benmcollins** [comment]
Yep, that's definitely what was happening. I have a fix coming soon.

I'm going to close this PR. Appreciate your help.

**Pull request closed without merging**
