### PR TITLE
time.h

### PR DESCRIPTION
**Pull request by RekGRpth**
to compile

### CODE REVIEW

**Comment by benmcollins** [comment]
Can you show me this compile failure? The only usage of time() is in the tests, and they already include time.h for that reason.

**Comment by RekGRpth** [comment]
```sh
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '18.205.93.2' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/rekgrpth/nginx:latest...
Step 1/6 : FROM rekgrpth/pdf
---> b1d573356285
Step 2/6 : CMD [ "nginx" ]
---> Running in a595a68f1028
Removing intermediate container a595a68f1028
---> ce9d514b9845
Step 3/6 : COPY NimbusSans-Regular.ttf /usr/local/share/fonts/
---> 55f379d75987
Step 4/6 : ENV GROUP=nginx USER=nginx
---> Running in 7e9489974178
Removing intermediate container 7e9489974178
---> 5e9b0ae16cd0
Step 5/6 : VOLUME "${HOME}"
---> Running in 29a865bd3dbc
Removing intermediate container 29a865bd3dbc
---> bd4fbf6c59f5
Step 6/6 : RUN set -ex && mkdir -p "${HOME}" && addgroup -S "${GROUP}" && adduser -D -S -h "${HOME}" -s /sbin/nologin -G "${GROUP}" "${USER}" && apk add --no-cache --virtual .build-deps bison cmake expat-dev expect-dev ffcall g++ gcc gd-dev gettext-dev git jansson-dev jpeg-dev libc-dev libunwind-dev linux-headers make openjpeg-dev openldap-dev pcre-dev perl-dev postgresql-dev readline-dev sqlite-dev zlib-dev && mkdir -p /usr/src && cd /usr/src && git clone --recursive https://github.com/RekGRpth/array-var-nginx-module.git && git clone --recursive https://github.com/RekGRpth/ctpp2.git && git clone --recursive https://github.com/RekGRpth/echo-nginx-module.git && git clone --recursive https://github.com/RekGRpth/encrypted-session-nginx-module.git && git clone --recursive https://github.com/RekGRpth/form-input-nginx-module.git && git clone --recursive https://github.com/RekGRpth/iconv-nginx-module.git && git clone --recursive https://github.com/RekGRpth/libjwt.git && git clone --recursive https://github.com/RekGRpth/nginx-access-plus.git && git clone --recursive https://github.com/RekGRpth/nginx-backtrace-ng.git && git clone --recursive https://github.com/RekGRpth/nginx-client-module.git && git clone --recursive https://github.com/RekGRpth/nginx_csrf_prevent.git && git clone --recursive https://github.com/RekGRpth/nginx-eval-module.git && git clone --recursive https://github.com/RekGRpth/NginxExecute.git && git clone --recursive https://github.com/RekGRpth/nginx.git && git clone --recursive https://github.com/RekGRpth/nginx-http-auth-digest.git && git clone --recursive https://github.com/RekGRpth/nginx-jwt-module.git && git clone --recursive https://github.com/RekGRpth/nginx-push-stream-module.git && git clone --recursive https://github.com/RekGRpth/nginx-upload-module.git && git clone --recursive https://github.com/RekGRpth/nginx-uuid4-module.git && git clone --recursive https://github.com/RekGRpth/ngx_ctpp2.git && git clone --recursive https://github.com/RekGRpth/ngx_http_auth_basic_ldap_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_captcha_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_headers_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_htmldoc_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_json_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_response_body_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_sign_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_substitutions_filter_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_zip_var_module.git && git clone --recursive https://github.com/RekGRpth/ngx_postgres.git && git clone --recursive https://github.com/RekGRpth/ngx_sqlite.git && git clone --recursive https://github.com/RekGRpth/replace-filter-nginx-module.git && git clone --recursive https://github.com/RekGRpth/set-misc-nginx-module.git && git clone --recursive https://github.com/RekGRpth/sregex.git && git clone --recursive https://github.com/RekGRpth/xss-nginx-module.git && cd /usr/src/sregex && make -j"$(nproc)" install && cd /usr/src/libjwt && cmake . -DBUILD_SHARED_LIBS=true && make -j"$(nproc)" install && cd /usr/src/ctpp2 && cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && make -j"$(nproc)" install && cd /usr/src/nginx && auto/configure "$(find .. -type f -name "config" | grep -v "\.git" | grep -v "\/t\/" | while read -r NAME; do echo "--add-dynamic-module=$(dirname "$NAME")"; done)" --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --group="${GROUP}" --http-client-body-temp-path=/var/cache/nginx/client_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --lock-path=/var/run/nginx.lock --modules-path=/usr/local/modules --pid-path=/var/run/nginx.pid --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --user="${USER}" --with-compat --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_realip_module --with-http_secure_link_module --with-http_ssl_module --with-http_sub_module --with-http_v2_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_realip_module --with-stream_ssl_module --with-threads && make -j"$(nproc)" install && rm -rf /usr/src && rm /etc/nginx/*.default && mkdir -p /var/cache/nginx && (strip /usr/local/bin/* /usr/local/lib/*.so /usr/local/modules/*.so /usr/sbin/nginx || true) && apk add --no-cache --virtual .nginx-rundeps apache2-utils $(scanelf --needed --nobanner --format '%n#p' --recursive /usr/sbin/nginx /usr/local | tr ',' '\n' | sort -u | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }') && apk del --no-cache .build-deps && ln -sf /usr/local/modules /etc/nginx/modules && ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
---> Running in 8149cf38bf2e
+ mkdir -p /home
+ addgroup -S nginx
+ adduser -D -S -h /home -s /sbin/nologin -G nginx nginx
+ apk add --no-cache --virtual .build-deps bison cmake expat-dev expect-dev ffcall g++ gcc gd-dev gettext-dev git jansson-dev jpeg-dev libc-dev libunwind-dev linux-headers make openjpeg-dev openldap-dev pcre-dev perl-dev postgresql-dev readline-dev sqlite-dev zlib-dev
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/93) Installing m4 (1.4.18-r1)
(2/93) Installing bison (3.4.2-r0)
(3/93) Installing libacl (2.2.53-r0)
(4/93) Installing libbz2 (1.0.8-r1)
(5/93) Installing expat (2.2.9-r0)
(6/93) Installing lz4-libs (1.9.2-r0)
(7/93) Installing xz-libs (5.2.4-r0)
(8/93) Installing zstd-libs (1.4.3-r0)
(9/93) Installing libarchive (3.4.0-r0)
(10/93) Installing nghttp2-libs (1.39.2-r2)
(11/93) Installing libcurl (7.66.0-r0)
(12/93) Installing ncurses-terminfo-base (6.1_p20191019-r0)
(13/93) Installing ncurses-terminfo (6.1_p20191019-r0)
(14/93) Installing ncurses-libs (6.1_p20191019-r0)
(15/93) Installing libgcc (9.2.0-r2)
(16/93) Installing rhash-libs (1.3.8-r0)
(17/93) Installing libstdc++ (9.2.0-r2)
(18/93) Installing libuv (1.33.1-r1)
(19/93) Installing cmake (3.15.4-r0)
(20/93) Installing pkgconf (1.6.3-r0)
(21/93) Installing expat-dev (2.2.9-r0)
(22/93) Installing expect-dev (5.45.4-r0)
(23/93) Installing ffcall (2.2-r1)
(24/93) Installing binutils (2.33.1-r0)
(25/93) Installing isl (0.18-r0)
(26/93) Installing libgomp (9.2.0-r2)
(27/93) Installing libatomic (9.2.0-r2)
(28/93) Installing mpfr4 (4.0.2-r1)
(29/93) Installing mpc1 (1.1.0-r1)
(30/93) Installing gcc (9.2.0-r2)
(31/93) Installing musl-dev (1.1.24-r0)
(32/93) Installing libc-dev (0.7.1-r0)
(33/93) Installing g++ (9.2.0-r2)
(34/93) Installing freetype (2.10.1-r0)
(35/93) Installing libwebp (1.0.3-r0)
(36/93) Installing libgd (2.2.5-r2)
(37/93) Installing gd (2.2.5-r2)
(38/93) Installing perl (5.30.0-r0)
(39/93) Installing gd-dev (2.2.5-r2)
(40/93) Installing xz (5.2.4-r0)
(41/93) Installing gettext-asprintf (0.20.1-r1)
(42/93) Installing libintl (0.20.1-r1)
(43/93) Installing gettext-libs (0.20.1-r1)
(44/93) Installing libxml2 (2.9.9-r2)
(45/93) Installing gettext (0.20.1-r1)
(46/93) Installing gettext-dev (0.20.1-r1)
(47/93) Installing pcre2 (10.33-r0)
(48/93) Installing git (2.23.0-r1)
(49/93) Installing perl-error (0.17028-r0)
(50/93) Installing perl-git (2.23.0-r1)
(51/93) Installing git-perl (2.23.0-r1)
(52/93) Installing jansson (2.12-r0)
(53/93) Installing jansson-dev (2.12-r0)
(54/93) Installing libjpeg-turbo-dev (2.0.3-r0)
(55/93) Installing jpeg-dev (8-r6)
(56/93) Installing libexecinfo (1.1-r1)
(57/93) Installing libexecinfo-dev (1.1-r1)
(58/93) Installing libunwind (1.2.1-r3)
(59/93) Installing libunwind-dev (1.2.1-r3)
(60/93) Installing linux-headers (4.19.36-r0)
(61/93) Installing make (4.2.1-r2)
(62/93) Installing openjpeg (2.3.1-r2)
(63/93) Installing openjpeg-dev (2.3.1-r2)
(64/93) Installing openssl-dev (1.1.1d-r2)
(65/93) Installing db (5.3.28-r1)
(66/93) Installing libsasl (2.1.27-r3)
(67/93) Installing cyrus-sasl-dev (2.1.27-r3)
(68/93) Installing libblkid (2.34-r0)
(69/93) Installing libuuid (2.34-r0)
(70/93) Installing libfdisk (2.34-r0)
(71/93) Installing libmount (2.34-r0)
(72/93) Installing libsmartcols (2.34-r0)
(73/93) Installing util-linux-dev (2.34-r0)
(74/93) Installing libldap (2.4.48-r1)
(75/93) Installing openldap-dev (2.4.48-r1)
(76/93) Installing libpcre16 (8.43-r0)
(77/93) Installing libpcre32 (8.43-r0)
(78/93) Installing pcre (8.43-r0)
(79/93) Installing libpcrecpp (8.43-r0)
(80/93) Installing pcre-dev (8.43-r0)
(81/93) Installing perl-utils (5.30.0-r0)
(82/93) Installing perl-dev (5.30.0-r0)
(83/93) Installing libpq (12.0-r0)
(84/93) Installing postgresql-libs (12.0-r0)
(85/93) Installing postgresql-dev (12.0-r0)
(86/93) Installing libhistory (8.0.1-r0)
(87/93) Installing ncurses-dev (6.1_p20191019-r0)
(88/93) Installing readline (8.0.1-r0)
(89/93) Installing readline-dev (8.0.1-r0)
(90/93) Installing sqlite-libs (3.30.1-r0)
(91/93) Installing sqlite-dev (3.30.1-r0)
(92/93) Installing zlib-dev (1.2.11-r3)
(93/93) Installing .build-deps (20191105.075451)
Executing busybox-1.31.0-r1.trigger
OK: 327 MiB in 124 packages
+ mkdir -p /usr/src
+ cd /usr/src
+ git clone --recursive https://github.com/RekGRpth/array-var-nginx-module.git
Cloning into 'array-var-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/ctpp2.git
Cloning into 'ctpp2'...
+ git clone --recursive https://github.com/RekGRpth/echo-nginx-module.git
Cloning into 'echo-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/encrypted-session-nginx-module.git
Cloning into 'encrypted-session-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/form-input-nginx-module.git
Cloning into 'form-input-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/iconv-nginx-module.git
Cloning into 'iconv-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/libjwt.git
Cloning into 'libjwt'...
+ git clone --recursive https://github.com/RekGRpth/nginx-access-plus.git
Cloning into 'nginx-access-plus'...
+ git clone --recursive https://github.com/RekGRpth/nginx-backtrace-ng.git
Cloning into 'nginx-backtrace-ng'...
+ git clone --recursive https://github.com/RekGRpth/nginx-client-module.git
Cloning into 'nginx-client-module'...
+ git clone --recursive https://github.com/RekGRpth/nginx_csrf_prevent.git
Cloning into 'nginx_csrf_prevent'...
+ git clone --recursive https://github.com/RekGRpth/nginx-eval-module.git
Cloning into 'nginx-eval-module'...
+ git clone --recursive https://github.com/RekGRpth/NginxExecute.git
Cloning into 'NginxExecute'...
+ git clone --recursive https://github.com/RekGRpth/nginx.git
Cloning into 'nginx'...
+ git clone --recursive https://github.com/RekGRpth/nginx-http-auth-digest.git
Cloning into 'nginx-http-auth-digest'...
+ git clone --recursive https://github.com/RekGRpth/nginx-jwt-module.git
Cloning into 'nginx-jwt-module'...
+ git clone --recursive https://github.com/RekGRpth/nginx-push-stream-module.git
Cloning into 'nginx-push-stream-module'...
+ git clone --recursive https://github.com/RekGRpth/nginx-upload-module.git
Cloning into 'nginx-upload-module'...
+ git clone --recursive https://github.com/RekGRpth/nginx-uuid4-module.git
Cloning into 'nginx-uuid4-module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_ctpp2.git
Cloning into 'ngx_ctpp2'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_auth_basic_ldap_module.git
Cloning into 'ngx_http_auth_basic_ldap_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_captcha_module.git
Cloning into 'ngx_http_captcha_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_headers_module.git
Cloning into 'ngx_http_headers_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_htmldoc_module.git
Cloning into 'ngx_http_htmldoc_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_json_module.git
Cloning into 'ngx_http_json_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_response_body_module.git
Cloning into 'ngx_http_response_body_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_sign_module.git
Cloning into 'ngx_http_sign_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_substitutions_filter_module.git
Cloning into 'ngx_http_substitutions_filter_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_http_zip_var_module.git
Cloning into 'ngx_http_zip_var_module'...
+ git clone --recursive https://github.com/RekGRpth/ngx_postgres.git
Cloning into 'ngx_postgres'...
+ git clone --recursive https://github.com/RekGRpth/ngx_sqlite.git
Cloning into 'ngx_sqlite'...
+ git clone --recursive https://github.com/RekGRpth/replace-filter-nginx-module.git
Cloning into 'replace-filter-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/set-misc-nginx-module.git
Cloning into 'set-misc-nginx-module'...
+ git clone --recursive https://github.com/RekGRpth/sregex.git
Cloning into 'sregex'...
+ git clone --recursive https://github.com/RekGRpth/xss-nginx-module.git
Cloning into 'xss-nginx-module'...
+ cd /usr/src/sregex
+ nproc
+ make -j1 install
CC src/sregex/sre_palloc.o
CC src/sregex/sre_regex.o
CC src/sregex/sre_yyparser.o
CC src/sregex/sre_regex_compiler.o
CC src/sregex/sre_vm_bytecode.o
CC src/sregex/sre_vm_thompson.o
CC src/sregex/sre_vm_pike.o
CC src/sregex/sre_capture.o
CC src/sregex/sre_vm_thompson_jit.o
In file included from src/sregex/sre_vm_thompson_jit.c:16:
./dynasm/dasm_x86.h: In function 'dasm_put':
./dynasm/dasm_x86.h:207:2: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
207 | if (*p++ == 1 && *p == DASM_DISP) mrm = n; continue;
| ^~
./dynasm/dasm_x86.h:207:45: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
207 | if (*p++ == 1 && *p == DASM_DISP) mrm = n; continue;
| ^~~~~~~~
DYNLINK libsregex.so
SYMLINK libsregex.so.0
AR libsregex.a
ar: `u' modifier ignored since `D' is the default (see `U')
CC src/sre_cli.o
LINK sregex-cli
==== Installing sregex 0.0.1 to /usr/local ====
mkdir -p /usr/local/include/sregex /usr/local/lib /usr/local/bin
install -m 0755 sregex-cli /usr/local/bin/sregex-cli
install -m 0644 src/sregex/sregex.h src/sregex/ddebug.h /usr/local/include/sregex
install -m 0755 libsregex.so /usr/local/lib/libsregex.so.0.0.1
ldconfig -n /usr/local/lib
ln -sf libsregex.so.0.0.1 /usr/local/lib/libsregex.so
ln -sf libsregex.so.0.0.1 /usr/local/lib/libsregex.so.0
==== Successfully installed sregex 0.0.1 to /usr/local ====
+ cd /usr/src/libjwt
+ cmake . '-DBUILD_SHARED_LIBS=true'
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1d")
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3")
-- Found LibJansson: /usr/lib/libjansson.so
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/libjwt
+ nproc
+ make -j1 install
Scanning dependencies of target jwt
[ 12%] Building C object libjwt/CMakeFiles/jwt.dir/base64.c.o
[ 25%] Building C object libjwt/CMakeFiles/jwt.dir/jwt-openssl.c.o
[ 37%] Building C object libjwt/CMakeFiles/jwt.dir/jwt.c.o
In file included from /usr/src/libjwt/libjwt/jwt.c:13:
/usr/src/libjwt/include/jwt.h:888:64: error: unknown type name 'time_t'
888 | JWT_EXPORT int jwt_valid_set_now(jwt_valid_t *jwt_valid, const time_t now);
| ^~~~~~
In file included from /usr/src/libjwt/libjwt/jwt.c:15:
/usr/src/libjwt/libjwt/jwt-private.h:23:2: error: unknown type name 'time_t'
23 | time_t now;
| ^~~~~~
/usr/src/libjwt/libjwt/jwt.c:1328:53: error: unknown type name 'time_t'
1328 | int jwt_valid_set_now(jwt_valid_t *jwt_valid, const time_t now)
| ^~~~~~
/usr/src/libjwt/libjwt/jwt.c: In function 'jwt_validate':
/usr/src/libjwt/libjwt/jwt.c:1384:2: error: unknown type name 'time_t'; did you mean 'size_t'?
1384 | time_t jwt_exp = get_js_int(jwt->grants, "exp");
| ^~~~~~
| size_t
/usr/src/libjwt/libjwt/jwt.c:1392:2: error: unknown type name 'time_t'; did you mean 'size_t'?
1392 | time_t jwt_nbf = get_js_int(jwt->grants, "nbf");
| ^~~~~~
| size_t
make[2]: *** [libjwt/CMakeFiles/jwt.dir/build.make:89: libjwt/CMakeFiles/jwt.dir/jwt.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: libjwt/CMakeFiles/jwt.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
Removing intermediate container 8149cf38bf2e
The command '/bin/sh -c set -ex && mkdir -p "${HOME}" && addgroup -S "${GROUP}" && adduser -D -S -h "${HOME}" -s /sbin/nologin -G "${GROUP}" "${USER}" && apk add --no-cache --virtual .build-deps bison cmake expat-dev expect-dev ffcall g++ gcc gd-dev gettext-dev git jansson-dev jpeg-dev libc-dev libunwind-dev linux-headers make openjpeg-dev openldap-dev pcre-dev perl-dev postgresql-dev readline-dev sqlite-dev zlib-dev && mkdir -p /usr/src && cd /usr/src && git clone --recursive https://github.com/RekGRpth/array-var-nginx-module.git && git clone --recursive https://github.com/RekGRpth/ctpp2.git && git clone --recursive https://github.com/RekGRpth/echo-nginx-module.git && git clone --recursive https://github.com/RekGRpth/encrypted-session-nginx-module.git && git clone --recursive https://github.com/RekGRpth/form-input-nginx-module.git && git clone --recursive https://github.com/RekGRpth/iconv-nginx-module.git && git clone --recursive https://github.com/RekGRpth/libjwt.git && git clone --recursive https://github.com/RekGRpth/nginx-access-plus.git && git clone --recursive https://github.com/RekGRpth/nginx-backtrace-ng.git && git clone --recursive https://github.com/RekGRpth/nginx-client-module.git && git clone --recursive https://github.com/RekGRpth/nginx_csrf_prevent.git && git clone --recursive https://github.com/RekGRpth/nginx-eval-module.git && git clone --recursive https://github.com/RekGRpth/NginxExecute.git && git clone --recursive https://github.com/RekGRpth/nginx.git && git clone --recursive https://github.com/RekGRpth/nginx-http-auth-digest.git && git clone --recursive https://github.com/RekGRpth/nginx-jwt-module.git && git clone --recursive https://github.com/RekGRpth/nginx-push-stream-module.git && git clone --recursive https://github.com/RekGRpth/nginx-upload-module.git && git clone --recursive https://github.com/RekGRpth/nginx-uuid4-module.git && git clone --recursive https://github.com/RekGRpth/ngx_ctpp2.git && git clone --recursive https://github.com/RekGRpth/ngx_http_auth_basic_ldap_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_captcha_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_headers_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_htmldoc_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_json_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_response_body_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_sign_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_substitutions_filter_module.git && git clone --recursive https://github.com/RekGRpth/ngx_http_zip_var_module.git && git clone --recursive https://github.com/RekGRpth/ngx_postgres.git && git clone --recursive https://github.com/RekGRpth/ngx_sqlite.git && git clone --recursive https://github.com/RekGRpth/replace-filter-nginx-module.git && git clone --recursive https://github.com/RekGRpth/set-misc-nginx-module.git && git clone --recursive https://github.com/RekGRpth/sregex.git && git clone --recursive https://github.com/RekGRpth/xss-nginx-module.git && cd /usr/src/sregex && make -j"$(nproc)" install && cd /usr/src/libjwt && cmake . -DBUILD_SHARED_LIBS=true && make -j"$(nproc)" install && cd /usr/src/ctpp2 && cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && make -j"$(nproc)" install && cd /usr/src/nginx && auto/configure "$(find .. -type f -name "config" | grep -v "\.git" | grep -v "\/t\/" | while read -r NAME; do echo "--add-dynamic-module=$(dirname "$NAME")"; done)" --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --group="${GROUP}" --http-client-body-temp-path=/var/cache/nginx/client_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --lock-path=/var/run/nginx.lock --modules-path=/usr/local/modules --pid-path=/var/run/nginx.pid --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --user="${USER}" --with-compat --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_realip_module --with-http_secure_link_module --with-http_ssl_module --with-http_sub_module --with-http_v2_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_realip_module --with-stream_ssl_module --with-threads && make -j"$(nproc)" install && rm -rf /usr/src && rm /etc/nginx/*.default && mkdir -p /var/cache/nginx && (strip /usr/local/bin/* /usr/local/lib/*.so /usr/local/modules/*.so /usr/sbin/nginx || true) && apk add --no-cache --virtual .nginx-rundeps apache2-utils $(scanelf --needed --nobanner --format '%n#p' --recursive /usr/sbin/nginx /usr/local | tr ',' '\n' | sort -u | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }') && apk del --no-cache .build-deps && ln -sf /usr/local/modules /etc/nginx/modules && ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log' returned a non-zero code: 2```

**Comment by benmcollins** [comment]
Thanks. So this is something in your clone, not master in my repo.

**Comment by benmcollins** [comment]
And I'm wrong...needed to pull the latest.

**Pull request merged**
